version: '3.8'

services:
  app:
    build: .
    image: nodeapp
    ports:
      - 80:8080
    environment:
      DB_USERNAME: reading_list_app
      DB_PASSWORD: password
      DB_DATABASE: reading_list
      DB_HOST: postgres
    volumes:
      - ".:/app"
    depends_on:
      - db
    command: sh -c "./wait-for db:5432 -- npm run build-start"


  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: reading_list_app
      POSTGRES_DB: reading_list
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      pgnodeapp:
        aliases:
          - "postgres"

networks:
  pgnodeapp:
    driver: bridge

volumes:
  postgres-db:
